# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
# NumPy version:
print("Numpy version:")
print(np.__version__)

# NumPy configuration
print("\nNumPy Configuration:")
np.show_config()

Numpy version:
2.4.4

NumPy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35225",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.31.188.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-mo_5b201/cp312-win_amd64/build/venv/Lib/site-packa

c:\Users\HAZEL\Desktop\Python_Learning\venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr = np.array([1,2,3,4,5])

#memory size
print(arr.nbytes)

40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
# null vector of size 10
vector = np.zeros(10)

#set the fifth value to 1
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vector = np.arange(10,20)
reversed_vector = vector[::-1]
print(reversed_vector)

[19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
values = np.arange(9)
matrix = values.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
array = np.random.random((3,3,3))
print(array)

[[[0.33105874 0.73154031 0.16815292]
  [0.37922157 0.19333543 0.20251223]
  [0.34268298 0.16067267 0.08181627]]

 [[0.60554895 0.77739034 0.7746124 ]
  [0.65083951 0.32389523 0.26148932]
  [0.37903228 0.12132949 0.1267627 ]]

 [[0.90020205 0.53149147 0.52974161]
  [0.15765148 0.40845166 0.93810418]
  [0.05258677 0.44452278 0.69137098]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [16]:
arr = np.random.random((10,10))

min_value = np.min(arr)
max_value = np.max(arr)

print(min_value)
print(max_value)


0.035489891167927
0.9970920309650586


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
vector = np.random.random(30)
mean_value = np.mean(vector)
print(vector)
print(mean_value)


[0.39144347 0.1513194  0.94125156 0.27766298 0.53151812 0.94162069
 0.4702633  0.53327965 0.39274345 0.64105356 0.6287493  0.26069063
 0.83684862 0.73048621 0.19233144 0.73692401 0.82442861 0.31147114
 0.0163393  0.43177413 0.61961438 0.4444638  0.64344859 0.24329489
 0.88236471 0.10296884 0.6218833  0.26812976 0.44581026 0.4133872 ]
0.4975855107841041


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
